version: '3.6'
services:
    db:
        env_file:
            - .env
        container_name: ${PROJECT_NAME}-database
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            - db
    php:
        env_file:
          - .env
        container_name: ${PROJECT_NAME}-php-fpm
        build: ./setup/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./src/backend:/var/www/html:cached
        depends_on:
            - db
        networks:
            - db
            - php
    react:
        env_file:
            - .env
        container_name: ${PROJECT_NAME}-react-app
        build: ./setup/node
        command: >
            sh -c "yarn install && yarn start"

        volumes:
            - ./src/frontend:/usr/app/
        ports:
            - "3000:3000"
        networks:
            - react

    nginx:
        env_file:
            - .env
        container_name: ${PROJECT_NAME}-nginx
        build: ./setup/nginx
        ports:
            - "80:80"
        depends_on:
            - php
            - react
        networks:
            - php
            - react
        volumes:
            - ./src/logs/nginx:/var/log/nginx:cached
            - ./src/backend:/var/www/html:cached
            - ./src/frontend:/var/www/app:cached

networks:
    db:
    php:
    react:
